# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RACS2Bridge_std_msgs.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'RACS2Bridge_std_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRACS2Bridge_std_msgs.proto\"\xf3\x02\n\x14RACS2Bridge_std_msgs\x12\x11\n\tbool_data\x18\x01 \x01(\x08\x12\x12\n\nfloat_data\x18\x02 \x01(\x02\x12\x13\n\x0b\x64ouble_data\x18\x03 \x01(\x01\x12\x12\n\nint32_data\x18\x04 \x01(\x05\x12\x12\n\nint64_data\x18\x05 \x01(\x03\x12\x13\n\x0bstring_data\x18\x06 \x01(\t\x12\x13\n\x0buint32_data\x18\x07 \x01(\r\x12\x13\n\x0buint64_data\x18\x08 \x01(\x04\x12\x1e\n\x12\x66loat32_array_data\x18\t \x03(\x02\x42\x02\x10\x01\x12\x1e\n\x12\x66loat64_array_data\x18\n \x03(\x01\x42\x02\x10\x01\x12\x1c\n\x10int32_array_data\x18\x0b \x03(\x05\x42\x02\x10\x01\x12\x1c\n\x10int64_array_data\x18\x0c \x03(\x03\x42\x02\x10\x01\x12\x1d\n\x11uint32_array_data\x18\r \x03(\rB\x02\x10\x01\x12\x1d\n\x11uint64_array_data\x18\x0e \x03(\x04\x42\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RACS2Bridge_std_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['float32_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['float32_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['float64_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['float64_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['int32_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['int32_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['int64_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['int64_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['uint32_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['uint32_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['uint64_array_data']._loaded_options = None
  _globals['_RACS2BRIDGE_STD_MSGS'].fields_by_name['uint64_array_data']._serialized_options = b'\020\001'
  _globals['_RACS2BRIDGE_STD_MSGS']._serialized_start=31
  _globals['_RACS2BRIDGE_STD_MSGS']._serialized_end=402
# @@protoc_insertion_point(module_scope)
